id: P008129
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13780
  title: ནག་རྩིས་སྣང་སྲིད་མེ་ལོང་དང་འབྲས་རྩིས་བདེན་དོན་སྙིང་པོ།
  author: ''
  volumes:
    85f2edfaaf724e02a90b2ca54b58e027:
      image_group_id: I1KG15279
      title: ''
      volume_number: 1
      total_pages: 306
ebook_metadata:
  title: ནག་རྩིས་སྣང་སྲིད་མེ་ལོང་དང་འབྲས་རྩིས་བདེན་དོན་སྙིང་པོ།
  author: ''
  sku: P008129
  cover: cover.jpg
  layers:
  - pagination
