id: P008129
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:03:32.085424
source_metadata:
  id: bdr:W1KG13780
  title: ནག་རྩིས་སྣང་སྲིད་མེ་ལོང་དང་འབྲས་རྩིས་བདེན་དོན་སྙིང་པོ།
  author: ''
  volumes:
    a53feae2a40e4f70b3c462291287655e:
      image_group_id: I1KG15279
      title: Volume 1 of nag rtsis snang srid me long dang 'bras rtsis bden don snying
        po/
      volume_number: 1
      total_pages: 306
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
